platform :ios, :deployment_target => "8.0"

def shared_dependencies
   pod "acceptSDK", :path => '../'
   pod "acceptSDK/Spire", :path => '../'
end

target 'Tests' do
    shared_dependencies
end

target 'AcceptDemo' do
    shared_dependencies
end

post_install do |installer_representation|
  installer_representation.pods_project.targets.each do |target|
   target.build_configurations.each do |config|
	   config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
       config.build_settings['ENABLE_STRICT_OBJC_MSGSEND'] = 'NO'
       config.build_settings['ENABLE_BITCODE'] = 'NO'
   end
  end
end


